### ISSUE TITLE
Add support for post meta fields to be included in the REST API 

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik#174]
For https://github.com/bobbingwide/sb-field-block I need to be able register the fields that will be displayable using the REST API.

### Requirements

- To be able to register REST fields for each post type
- To be able to determine whether or not a field should be registered to the REST API
- To set the field's $args : type, description, default and single

### Proposed solution
- [x] Extend `bw_register_field_for_object_type()` in `includes\bw_register.php`
- [ ] Extend `bw_register_field` $args to support `#rest` - default same value of `#theme`
- [x] To use a default auth_callback function if `#form` is true.
- [x] Set the description from `#title`

Note: For bigram I wrote a new function to register the `_seen_before` post meta field, registering it for both `bigram` and `post` post types.

```
/**
 * Registers the post meta to the REST API.
 *
 * register_post_meta() calls register_meta().
 *
 * @param $field
 * @param $post_type
 */
function bigram_register_post_meta( $field, $post_type, $description ) {
    global $wp_meta_keys;
    bw_trace2( $wp_meta_keys, 'wp_meta_keys before' );
    $registered =  register_post_meta( $post_type, $field,
        array('show_in_rest' => true,
            'single' => true,
            'type' => 'string',
            'auth_callback' => 'bigram_auth_callback',
            'description' => $description
        )
    );
    bw_trace2( $registered, 'registered?', false);
    bw_trace2( $wp_meta_keys, 'wp_meta_keys after', false );

}

**Comment by bobbingwide** [comment]
> Extend bw_register_field $args to support #rest - default same value of #theme

This wasn't necessary. You have to change the `bw_register_field-for_object_type()` calls to enable each field to be included in the REST API by product type.

> To use a default auth_callback function

The default auth_callback function is `bw_auth_callback()`. 

>  if #form is true.

This is defined in `bw_maybe_register_post_meta()`, which is called by `bw_register_field_for_object_type()` when `$rest` is `true`

This was originally delivered in oik v4.2.0 in May. Closing therefore.
